version: '3.8'
services:
  proxyipchecker:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GO_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M